# -*-coding: utf-8 -*-

__title__ = "Copy Elemement" #Name of the button displayed in Revit UI
__doc__   ="""This is simple tool to Copy Elemement With Revit API """ #Button Description shown in Revit UI
__version__ = "Version = 1.0"
__doc__ = """ Version = 1.0
Date    = 26.08.2022
_____________________________________________________________________
Description:

Test code about Copying Elements 
using Revit API
______________________________________
Author: Dmytro Khom"""
__author__ = "Dmytro Khom"



# â•¦â•”â•¦â•—â•”â•â•—â•”â•â•—â•¦â•â•—â•”â•¦â•—â•”â•â•—
# â•‘â•‘â•‘â•‘â• â•â•â•‘ â•‘â• â•¦â• â•‘ â•šâ•â•—
# â•©â•© â•©â•©  â•šâ•â•â•©â•šâ• â•© â•šâ•â• IMPORTS
# =======================================================================

# Regular + Autodesk
from Autodesk.Revit.DB import *    #Import everything from DB (Very good for beginners and development)
from Autodesk.Revit.DB.Structure import StructuralType
# .NET IMPORT
import clr
clr.AddReference('System')

# # pyRevit
from pyrevit import revit, forms
from pyrevit.forms import select_views

from System.Collections.Generic import List
# # from Autodesk.Revit.DB import Transaction, Element, ElementId, FilteredElementCollector, Level, BuiltInCategory



# â•¦  â•¦â•”â•â•—â•¦â•â•—â•¦â•”â•â•—â•”â•— â•¦  â•”â•â•—â•”â•â•—
# â•šâ•—â•”â•â• â•â•£â• â•¦â•â•‘â• â•â•£â• â•©â•—â•‘  â•‘â•£ â•šâ•â•—
#  â•šâ• â•© â•©â•©â•šâ•â•©â•© â•©â•šâ•â•â•©â•â•â•šâ•â•â•šâ•â• VARIABLES
# ===========================================================================
# from pyrevit.revit import uidoc, doc, app #Alternative
doc    = __revit__.ActiveUIDocument.Document
uidoc  = __revit__.ActiveUIDocument
app    = __revit__.Application


# â•”â•â•—â•¦ â•¦â•”â•—â•”â•”â•â•—â•”â•¦â•—â•¦â•”â•â•—â•”â•—â•”â•”â•â•—
# â• â•£ â•‘ â•‘â•‘â•‘â•‘â•‘   â•‘ â•‘â•‘ â•‘â•‘â•‘â•‘â•šâ•â•—
# â•š  â•šâ•â•â•â•šâ•â•šâ•â• â•© â•©â•šâ•â•â•â•šâ•â•šâ•â• FUNCTIONS
# ===========================================================================


# â•”â•â•—â•¦  â•”â•â•—â•”â•â•—â•”â•â•—â•”â•â•—â•”â•â•—
# â•‘  â•‘  â• â•â•£â•šâ•â•—â•šâ•â•—â•‘â•£ â•šâ•â•—
# â•šâ•â•â•©â•â•â•© â•©â•šâ•â•â•šâ•â•â•šâ•â•â•šâ•â• CLASSES
# ===========================================================================


# â•”â•¦â•—â•”â•â•—â•¦â•”â•—â•”
# â•‘â•‘â•‘â• â•â•£â•‘â•‘â•‘â•‘
# â•© â•©â•© â•©â•©â•â•šâ• MAIN

# ğŸŸ¢ â•”â•â•—â•”â•â•—â•”â•â•—â•¦ â•¦  â•¦ â•¦â•¦â•”â•¦â•—â•¦ â•¦  â•¦  â•¦â•”â•â•—â•”â•â•—â•”â•¦â•—â•”â•â•—â•¦â•â•—
# ğŸŸ¢ â•‘  â•‘ â•‘â• â•â•â•šâ•¦â•  â•‘â•‘â•‘â•‘ â•‘ â• â•â•£  â•šâ•—â•”â•â•‘â•£ â•‘   â•‘ â•‘ â•‘â• â•¦â•
# ğŸŸ¢ â•šâ•â•â•šâ•â•â•©   â•©   â•šâ•©â•â•© â•© â•© â•©   â•šâ• â•šâ•â•â•šâ•â• â•© â•šâ•â•â•©â•šâ• COPY WITH VECTOR

# ===========================================================================
# #ğŸ‘‰ Get Walls
# wallsToCopy = FilteredElementCollector(doc)\
#     .OfCategory(BuiltInCategory.OST_Walls)\
#     .WhereElementIsNotElementType()\
#     .ToElementIds()
#
# # ğŸ“Vector
# vector = XYZ(250, 500, 0)
#
# # ğŸ”“ Start Transaction
# t = Transaction(doc, __title__)
# t.Start()
#
# # âœ” Copy Elements
# ElementTransformUtils.CopyElements(doc, wallsToCopy, vector)
#
# #for wall in wallsToCopy:
# #         ElementTransformUtils.CopyElement(doc, wall, vector)
#
#
# # ğŸ”’ End Transaction
# t.Commit()




# ğŸŸ¡ â•”â•â•—â•”â•â•—â•”â•â•—â•¦ â•¦  â•”â•— â•”â•â•—â•”â•¦â•—â•¦ â•¦â•”â•â•—â•”â•â•—â•”â•—â•”  â•¦  â•¦â•¦â•”â•â•—â•¦ â•¦â•”â•â•—
# ğŸŸ¡ â•‘  â•‘ â•‘â• â•â•â•šâ•¦â•  â• â•©â•—â•‘â•£  â•‘ â•‘â•‘â•‘â•‘â•£ â•‘â•£ â•‘â•‘â•‘  â•šâ•—â•”â•â•‘â•‘â•£ â•‘â•‘â•‘â•šâ•â•—
# ğŸŸ¡ â•šâ•â•â•šâ•â•â•©   â•©   â•šâ•â•â•šâ•â• â•© â•šâ•©â•â•šâ•â•â•šâ•â•â•â•šâ•   â•šâ• â•©â•šâ•â•â•šâ•©â•â•šâ•â• COPY BETWEEN VIEWS
# ===========================================================================
# # ğŸ‘‰ Get TextNotes
# textToCopy = FilteredElementCollector(doc, doc.ActiveView.Id)\
#     .OfCategory(BuiltInCategory.OST_TextNotes)\
#     .WhereElementIsNotElementType()\
#     .ToElementIds()
#
# # ğŸ‘ Get Views
# src_view =  doc.ActiveView
# dest_view = select_views(__title__,multiple=False)
#
# # âš™ Transform & Options
# transform = Transform.Identity
# opts      = CopyPasteOptions()
#
# # # ğŸ”“ Start Transaction
# t = Transaction(doc, __title__)
# t.Start()
#
# # âœ” Copy Elements
# ElementTransformUtils.CopyElements(src_view, textToCopy, dest_view, transform, opts)
#
# # # ğŸ”’ End Transaction
# t.Commit()


# ğŸŸ  â•”â•â•—â•”â•â•—â•”â•â•—â•¦ â•¦  â•”â•— â•”â•â•—â•”â•¦â•—â•¦ â•¦â•”â•â•—â•”â•â•—â•”â•—â•”  â•”â•â•—â•¦â•â•—â•”â•â•— â•¦â•”â•â•—â•”â•â•—â•”â•¦â•—â•”â•â•—
# ğŸŸ  â•‘  â•‘ â•‘â• â•â•â•šâ•¦â•  â• â•©â•—â•‘â•£  â•‘ â•‘â•‘â•‘â•‘â•£ â•‘â•£ â•‘â•‘â•‘  â• â•â•â• â•¦â•â•‘ â•‘ â•‘â•‘â•£ â•‘   â•‘ â•šâ•â•—
# ğŸŸ  â•šâ•â•â•šâ•â•â•©   â•©   â•šâ•â•â•šâ•â• â•© â•šâ•©â•â•šâ•â•â•šâ•â•â•â•šâ•  â•©  â•©â•šâ•â•šâ•â•â•šâ•â•šâ•â•â•šâ•â• â•© â•šâ•â• COPY BETWEEN PROJECTS
# # ===========================================================================
# #ğŸ‘‰ Get Walls
# wallsToCopy = FilteredElementCollector(doc)\
#     .OfCategory(BuiltInCategory.OST_Walls)\
#     .WhereElementIsNotElementType()\
#     .ToElementIds()
#
# #ğŸ Get all Docs
# all_docs = list(app.Documents)
# doc_A = all_docs[0]
# doc_B = all_docs[1]
#
# # âš™ Transform & Options
# transform = Transform.Identity
# opts      = CopyPasteOptions()
#
#
# # # ğŸ”“ Start Transaction
# t = Transaction(doc_B, __title__)
# t.Start()
#
# # âœ” Copy Elements
# ElementTransformUtils.CopyElements(doc_A, wallsToCopy, doc_B, transform, opts)
#
# # # ğŸ”’ End Transaction
# t.Commit()



